name: Cloudflare Cache Purge

on:
  push:
    branches:
      - myblog # 这里的分支名称可以根据自己的情况进行修改
  workflow_dispatch:

jobs:
  purge_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Purge Cloudflare Cache
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        run: |
          curl -sSX POST "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/purge_cache" \
            -H "Authorization: Bearer ${CF_API_KEY}" \
            -H "Content-Type: application/json" \
            -H "X-Auth-Email: chan@frostleaf.dev" \
            --data '{"purge_everything":true}'

  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          retain_days: 5
